config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resources :books do
    get :search, on: :collection
  end

  devise_for :users, skip: [:password, :registrations ]

  as :user do
    get "users/sign_up", to: "devise/registrations#new", as: :new_user_registration
    post "users", to: "devise/registrations#create", as: :user_registration
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  update_index("books") { self }

  has_one_attached :book_cover
  has_one_attached :book_content

  validates :title, :author, presence: true, length: { in: 1..50 }
  validates :isbn, presence: true, length: { is: 13 }
  validates :description, length: { maximum: 1000 }

  scope :ordered, -> { order(:title) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  validates :username, :first_name, :last_name, :email, presence: true
  validates :email, :username, uniqueness: true
  validates :username, length: { minimum: 3, maximum: 20 },
                       format: { with: /\A[a-z0-9_]+\z/,
                       message: "only allows lowercase letters, numbers, and underscores" }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = collection
  end

  def show
    @book = resourse
  end

  def new
    @book = Book.new
  end

  def edit
    @book = resourse
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to book_path(@book), notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @book = resourse

    if @book.update(book_params)
      redirect_to book_path(@book), notice: "Book was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    resourse.destroy

    redirect_to books_path, notice: "Book was successfully destroyed.", status: :see_other
  end

  def search
    query = search_params[:query]

    if query.present?
      @books = BookSearch.search(query)

      if @books.any?
        flash.now[:notice] = "We found #{@books.count} books"
      else
        flash.now[:alert] = "No books match your search."
      end

      render :index
    else
      redirect_back(fallback_location: root_path, alert: "Search field cannot be empty.")
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :isbn, :book_cover, :book_content, :description)
  end

  def search_params
    params.require(:search).permit(:query)
  end

  def collection
    Book.ordered
  end

  def resourse
    collection.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_book_cover(book)
    image = book.book_cover.attached? ? book.book_cover : "book_cover.jpg"

    image_tag image, class: "book-img"
  end
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="book-card">
  <div class="book-cover">
    <%= display_book_cover(book) %>
  </div>
  <div class="flex flex-col justify-between flex-grow p-6">
    <div>
      <h2 class="card-title"><%= book.title %></h2>
      <p class="card-author"><%= book.author %></p>
      <p class="mb-2 text-sm text-gray-700">ISBN: <%= book.isbn %></p>
      <p class="card-text"><%= book.description %></p>
    </div>
    <div class="mt-auto">
      <%= link_to "Show", book, class: "card-button" %>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(book, url: polymorphic_path(book)) do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :isbn, hint: "13 digits ISBN format" %>
  <%= f.input :book_cover, as: :file %>
  <%= f.input :book_content, as: :file %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/books/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">Editing book</h1>

  <%= render "books/form", book: @book %>

  <%= link_to "Show this book", book_path, class: "btn" %>
  <%= link_to "Back to books", books_path, class: "btn" %>
  <%= button_to "Destroy this book", book_path(@book), method: :delete, class: "btn mt-10 bg-red-200" %>
</div>

app/views/books/index.html.erb
<div class="w-full">
  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold">Books</h1>
  </div>

  <div class="min-w-full">
    <%= render partial: "books/book", collection: @books %>
  </div>
</div>

app/views/books/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New book</h1>

  <%= render "books/form", book: @book %>

  <%= link_to "Back to books", books_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/books/show.html.erb
<div class="show-container">
  <div class="show-card">
    <div class="show-cover">
      <%= display_book_cover(@book) %>
    </div>

    <div class="p-6">
      <%= link_to @book.title, edit_book_path(@book), class: "show-title" %>
      <h4 class="show-author"><%= @book.author %></h4>
      <p class="show-isbn">ISBN: <%= @book.isbn %></p>
      <p class="show-text"><%= @book.description %></p>
      <div class="mt-auto ">
        <%= link_to "Back to books", books_path, class: "card-button" %>
      </div>
    </div>
  </div>

  <% if current_user && @book.book_content.attached? %>
    <script src="https://acrobatservices.adobe.com/view-sdk/viewer.js"></script>
    <div id="adobe-dc-view" class="mt-8 show-card"></div>
    <div data-controller="adobe-viewer"
        data-url="<%= rails_blob_path(@book.book_content, only_path: true) %>"
        data-filename="<%= @book.book_content.filename %>"
        data-adobe-viewer-element-id="adobe-dc-view">
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Haven</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render partial: "shared/navbar" %>
      <%= render partial: "shared/flashes" %>
    </header>
    <main class="container flex px-5 mx-auto mt-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% flash.each do |type, msg| %>
  <div class="flash-<%= type %>">
    <%= msg %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="bg-slate-600">
  <nav class="navbar">
    <div class="nav-title-container">
      <span class="nav-title">Book <span class="haven">Haven</span></span>
    </div>
    <div class="nav-items">
      <div class="text-sm lg:flex-grow">
        <%= link_to "All Books", root_path, class: "nav-link" %>
        <%= link_to "New Book", new_book_path, class: "nav-link" %>
      </div>
      <div class="mx-10 ">
        <%= simple_form_for :search, url: search_books_path, method: :get, html: {  class: "flex items-center search-form", role: "search" } do |f| %>
          <%= f.input :query, as: :search, input_html: { class: "mt-3 border-teal-500", placeholder: "Search book..." }, label: false %>
          <%= f.submit "Search", class: "sign-button mx-4" %>
        <% end %>
      </div>
      <div class="flex items-center text-white">
        <% if user_signed_in? %>
          <span class="mr-2">Hello, <%= current_user.email %></span>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign-button" %>

        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: "sign-button" %>
        <% end %>
    </div>
    </div>
  </nav>
</div>